# Generated by Django 2.1.7 on 2019-05-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('who', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('ap', models.CharField(max_length=60)),
                ('am', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('ext', models.CharField(blank=True, max_length=5, null=True)),
                ('estado', models.BooleanField()),
                ('adminstate', models.BooleanField()),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=60, null=True)),
                ('mac', models.CharField(blank=True, max_length=17, null=True)),
                ('ns', models.CharField(blank=True, max_length=60, null=True)),
                ('ip', models.CharField(blank=True, max_length=60, null=True)),
                ('cambs', models.CharField(blank=True, max_length=60, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=60, null=True)),
                ('procesador', models.CharField(blank=True, max_length=60, null=True)),
                ('num_puertos', models.CharField(blank=True, max_length=60, null=True)),
                ('memoria_ram', models.CharField(blank=True, max_length=60, null=True)),
                ('disco_duro', models.CharField(blank=True, max_length=60, null=True)),
                ('lastupdate', models.CharField(blank=True, max_length=60, null=True)),
                ('idf', models.CharField(blank=True, max_length=60, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('depto', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Departamento')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='GruposTrabajo',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoincidencia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InstalacionSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('nofolio', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Equipo')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confiabilidad', models.IntegerField()),
                ('responsabilidad', models.IntegerField()),
                ('seguridad', models.IntegerField()),
                ('infrayservicios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('sala', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('edificio', 'piso', 'sala')},
        ),
        migrations.AddField(
            model_name='subdepartamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=models.SET(None), to='tt.Ubicacion'),
        ),
        migrations.AddField(
            model_name='orden',
            name='subdepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.SubDepartamento'),
        ),
        migrations.AddField(
            model_name='orden',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(None), to='tt.Satisfaccion'),
        ),
        migrations.AddField(
            model_name='orden',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoTrabajo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoEquipo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ordenes',
            field=models.ManyToManyField(blank=True, to='tt.Orden'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='subdepartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.SubDepartamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='trabajos',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.TipoTrabajo'),
        ),
        migrations.AddField(
            model_name='descripcion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Orden'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='grupoTrabajo',
            field=models.ManyToManyField(blank=True, to='tt.GruposTrabajo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=models.SET(None), to='tt.Ubicacion'),
        ),
    ]
