# Generated by Django 2.1.7 on 2019-02-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('ap', models.CharField(max_length=60)),
                ('am', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=60)),
                ('mac', models.CharField(max_length=60)),
                ('ns', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=60)),
                ('cambs', models.CharField(max_length=60)),
                ('sistema_operativo', models.CharField(max_length=60)),
                ('procesador', models.CharField(max_length=60)),
                ('num_puertos', models.CharField(max_length=60)),
                ('memoria_ram', models.CharField(max_length=60)),
                ('disco_duro', models.CharField(max_length=60)),
                ('idf', models.CharField(max_length=60)),
                ('caracteristicas', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GruposTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoincidencia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InstalacionSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('caracteristicas', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Equipo')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Incidencia')),
                ('instalacionsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.InstalacionSoft')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('idSatisfaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('confiabilidad', models.IntegerField()),
                ('responsabilidad', models.IntegerField()),
                ('seguridad', models.IntegerField()),
                ('infrayservicios', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('sala', models.IntegerField()),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoTrabajo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoEquipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Ubicacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ordenes',
            field=models.ManyToManyField(to='tt.Orden'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='trabajos',
            field=models.ManyToManyField(to='tt.TipoTrabajo'),
        ),
    ]
