# Generated by Django 2.1.7 on 2019-02-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='id',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='idTecnico',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
