# Generated by Django 2.1.7 on 2019-02-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0002_auto_20190222_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='idTecnico',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
