# Generated by Django 2.1.7 on 2019-03-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0002_empleado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.TipoTrabajo'),
        ),
    ]
