# Generated by Django 2.1.7 on 2019-02-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0003_auto_20190222_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='idEmpledo',
            new_name='idEmpleado',
        ),
    ]
