# Generated by Django 2.1.7 on 2019-03-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0003_auto_20190309_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ext',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
