# Generated by Django 2.1.7 on 2019-03-10 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0005_auto_20190309_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Ubicacion'),
        ),
    ]
