# Generated by Django 2.1.7 on 2019-03-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0007_auto_20190310_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='subdepto',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='equipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.Empleado'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.Marca'),
        ),
    ]
