# Generated by Django 2.1.7 on 2019-03-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0008_auto_20190316_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='equipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tt.Equipo'),
            preserve_default=False,
        ),
    ]
