# Generated by Django 2.1.7 on 2019-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0009_orden_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cambs',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='disco_duro',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='idf',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ip',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='mac',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='num_puertos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='procesador',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
