# Generated by Django 2.1.7 on 2019-03-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0010_auto_20190317_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.Departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='subdepartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.SubDepartamento'),
        ),
    ]
