# Generated by Django 2.1.7 on 2019-03-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0011_auto_20190318_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ns',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
