# Generated by Django 2.1.7 on 2019-03-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0012_auto_20190324_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='subdepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.SubDepartamento'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.Incidencia'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='instalacionsoft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.InstalacionSoft'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tt.Satisfaccion'),
        ),
    ]
