# Generated by Django 2.1.7 on 2019-03-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0013_auto_20190324_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='orden',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descripcion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt.Orden'),
        ),
    ]
