# Generated by Django 2.1.7 on 2019-04-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0014_auto_20190324_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='who',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
