# Generated by Django 2.1.7 on 2019-04-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0015_descripcion_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='uuid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=models.SET(None), to='tt.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='subdepartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.SubDepartamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajos',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.TipoTrabajo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='depto',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Departamento'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Empleado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Marca'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='tt.Incidencia'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(None), to='tt.Satisfaccion'),
        ),
        migrations.AlterField(
            model_name='subdepartamento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=models.SET(None), to='tt.Ubicacion'),
        ),
    ]
