# Generated by Django 2.1.7 on 2019-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0016_auto_20190415_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
