# Generated by Django 2.1.7 on 2019-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0018_auto_20190420_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
