# Generated by Django 2.1.7 on 2019-05-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0023_remove_orden_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='instalacionsoft',
        ),
    ]
