# Generated by Django 2.1.7 on 2019-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0024_remove_orden_instalacionsoft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacionsoft',
            name='estado',
        ),
        migrations.AddField(
            model_name='equipo',
            name='lastupdate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
